//! redb schema-migration round-trip
//! [src: .claude/plans/post-v1-roadmap/tier-02-redb-schema-migration.md].
//!
//! `v1_fixture_migrates_in_place_with_all_records_intact` opens a committed
//! redb database written at schema version 1 and asserts the adapter
//! migrates it to the current version with every record preserved.
//! `older_version_with_no_migration_path_returns_schema_mismatch` asserts the
//! v1 rebuild-on-mismatch error is still raised when no registered path
//! covers the on-disk version.
//!
//! The committed `fixtures/schema-v1.redb` is (re)generated by the
//! `#[ignore]`d `generate_v1_schema_fixture` helper.

use std::path::PathBuf;

use ariadne_core::{
    Changeset, EdgeKey, EdgeKind, EdgeRecord, FileId, FileRecord, IdEncode, Lang, ReadSnapshot,
    Span, Storage, StorageError, SymbolId, SymbolRecord, Visibility, WriteTxn,
};
use ariadne_storage::RedbStorage;
use redb::{Database, ReadableDatabase, TableDefinition};
use serde::{Deserialize, Serialize};

/// `META` table mirror — kept local so the test exercises only the adapter's
/// public surface, matching `tests/changeset.rs`.
const META: TableDefinition<'_, &str, u64> = TableDefinition::new("meta");

/// `SYMBOLS` table mirror — local so the v2 fixture generator can write v2
/// postcard bodies directly (the schema runtime by now encodes v3).
const SYMBOLS: TableDefinition<'_, &[u8], &[u8]> = TableDefinition::new("symbols");

/// Frozen v2 `SymbolRecord` layout — matches the four-field record that
/// shipped at `SCHEMA_VERSION = 2`. Postcard is non-self-describing
/// [src: <https://postcard.jamesmunns.com/wire-format>], so this struct
/// produces the exact byte-prefix a v3 `SymbolRecord` would inherit when
/// `visibility=Unknown` and `attributes=Vec::new()` (the migration's
/// default fill).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct SymbolRecordV2 {
    canonical_name: String,
    kind: String,
    defining_file: FileId,
    defining_span: Span,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/schema-v1.redb")
}

fn fixture_v2_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/schema-v2.redb")
}

fn fid(n: u32) -> FileId {
    FileId::new(n).expect("nonzero file id")
}

fn sid(n: u64) -> SymbolId {
    SymbolId::new(n).expect("nonzero symbol id")
}

/// The deterministic record set stored in the v1 fixture: 2 files, 3 symbols,
/// 2 edges. Both the generator and the round-trip assertions derive from it.
#[allow(clippy::type_complexity)]
fn known_records() -> (
    Vec<(FileId, FileRecord)>,
    Vec<(SymbolId, SymbolRecord)>,
    Vec<(EdgeKey, EdgeRecord)>,
) {
    let files = vec![
        (
            fid(1),
            FileRecord {
                path: "src/a.rs".to_owned(),
                lang: Lang::Rust,
                size: 100,
                blake3: [1u8; 32],
                mtime_ns: 11,
            },
        ),
        (
            fid(2),
            FileRecord {
                path: "src/b.rs".to_owned(),
                lang: Lang::Rust,
                size: 200,
                blake3: [2u8; 32],
                mtime_ns: 22,
            },
        ),
    ];
    let symbol = |id: u64, name: &str, file: u32, start: u32| {
        (
            sid(id),
            SymbolRecord {
                canonical_name: name.to_owned(),
                kind: "function".to_owned(),
                defining_file: fid(file),
                defining_span: Span {
                    file: fid(file),
                    byte_start: start,
                    byte_end: start + 5,
                },
                visibility: Visibility::Unknown,
                attributes: Vec::new(),
            },
        )
    };
    let symbols = vec![
        symbol(1, "a::one", 1, 10),
        symbol(2, "a::two", 1, 30),
        symbol(3, "b::three", 2, 10),
    ];
    let edge = |src: u64, kind: EdgeKind, dst: u64, file: u32| {
        (
            EdgeKey {
                src: sid(src),
                kind,
                dst: sid(dst),
            },
            EdgeRecord {
                source_span: Span {
                    file: fid(file),
                    byte_start: 0,
                    byte_end: 4,
                },
                evidence_lang: Lang::Rust,
                weight: 1,
            },
        )
    };
    let edges = vec![
        edge(1, EdgeKind::References, 2, 1),
        edge(2, EdgeKind::Imports, 3, 1),
    ];
    (files, symbols, edges)
}

fn known_changeset() -> Changeset {
    let (files, symbols, edges) = known_records();
    let mut cs = Changeset::new();
    for (id, rec) in files {
        cs = cs.upsert_file(id, rec);
    }
    for (id, rec) in symbols {
        cs = cs.upsert_symbol(id, rec);
    }
    for (key, rec) in edges {
        cs = cs.add_edge(key, rec);
    }
    cs
}

/// Reads the `schema_version` value directly from a redb file.
fn on_disk_schema_version(path: &std::path::Path) -> Option<u64> {
    let db = Database::open(path).expect("raw open");
    let read = db.begin_read().expect("begin_read");
    let meta = read.open_table(META).expect("open meta");
    meta.get("schema_version").expect("get").map(|g| g.value())
}

/// Regenerates the committed `fixtures/schema-v1.redb`. Ignored so a normal
/// test run never rewrites the committed binary; invoke with `--ignored`.
#[test]
#[ignore = "regenerates fixtures/schema-v1.redb; run manually with --ignored"]
fn generate_v1_schema_fixture() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let scratch = tmp.path().join("scratch.redb");
    {
        let storage = RedbStorage::open(&scratch).expect("open scratch");
        storage
            .begin_write()
            .expect("begin write")
            .apply(&known_changeset())
            .expect("apply");
    }
    // The current binary bootstraps at the current SCHEMA_VERSION; force the
    // on-disk version back to 1 so the fixture represents a real v1 database.
    let db = Database::open(&scratch).expect("raw open");
    let txn = db.begin_write().expect("begin_write");
    {
        let mut meta = txn.open_table(META).expect("open meta");
        meta.insert("schema_version", &1u64)
            .expect("downgrade version");
    }
    txn.commit().expect("commit");
    drop(db);

    let dest = fixture_path();
    std::fs::create_dir_all(dest.parent().expect("fixtures parent")).expect("mkdir fixtures");
    std::fs::copy(&scratch, &dest).expect("write fixture");
}

#[test]
fn v1_fixture_migrates_in_place_with_all_records_intact() {
    let fixture = fixture_path();
    assert!(
        fixture.exists(),
        "missing {} — run `generate_v1_schema_fixture` with --ignored",
        fixture.display(),
    );

    // `RedbStorage::open` migrates in place; copy so the committed fixture
    // stays pristine.
    let tmp = tempfile::tempdir().expect("tempdir");
    let work = tmp.path().join("index.redb");
    std::fs::copy(&fixture, &work).expect("copy fixture");
    assert_eq!(
        on_disk_schema_version(&work),
        Some(1),
        "fixture must be a v1 database",
    );

    // Open through the adapter: the v1 -> v2 chain runs.
    let storage = RedbStorage::open(&work).expect("v1 fixture must migrate, not error");
    let snap = storage.snapshot().expect("snapshot");

    let (files, symbols, edges) = known_records();
    for (id, rec) in &files {
        assert_eq!(
            snap.file(*id).expect("file lookup"),
            Some(rec.clone()),
            "file {id:?} survived migration",
        );
    }
    for (id, rec) in &symbols {
        let in_file = snap
            .symbols_in_file(rec.defining_file)
            .expect("symbols_in_file");
        assert!(in_file.contains(rec), "symbol {id:?} survived migration");
    }
    for (key, rec) in &edges {
        let out = snap.outgoing_edges(key.src).expect("outgoing_edges");
        assert!(
            out.contains(&(*key, rec.clone())),
            "edge {key:?} survived migration",
        );
    }
    assert_eq!(
        storage.revision().0,
        1,
        "revision counter survives migration",
    );

    drop(storage);
    assert_eq!(
        on_disk_schema_version(&work),
        Some(3),
        "schema version advanced to current on disk",
    );
}

#[test]
fn older_version_with_no_migration_path_returns_schema_mismatch() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let path = tmp.path().join("index.redb");
    drop(RedbStorage::open(&path).expect("bootstrap"));

    // Force an on-disk version older than any registered migration step.
    let db = Database::open(&path).expect("raw open");
    let txn = db.begin_write().expect("begin_write");
    {
        let mut meta = txn.open_table(META).expect("open meta");
        meta.insert("schema_version", &0u64).expect("insert");
    }
    txn.commit().expect("commit");
    drop(db);

    match RedbStorage::open(&path) {
        Err(StorageError::SchemaMismatch { found, expected }) => {
            assert_eq!((found, expected), (0, 3), "no path -> rebuild signal");
        }
        other => panic!("expected SchemaMismatch, got {other:?}"),
    }
}

/// Known v2 symbol records — the deterministic set the v2 fixture stores
/// and the v2 -> v3 migration test asserts survived.
fn known_symbols_v2() -> Vec<(SymbolId, SymbolRecordV2)> {
    let symbol = |id: u64, name: &str, file: u32, start: u32| {
        (
            sid(id),
            SymbolRecordV2 {
                canonical_name: name.to_owned(),
                kind: "function".to_owned(),
                defining_file: fid(file),
                defining_span: Span {
                    file: fid(file),
                    byte_start: start,
                    byte_end: start + 5,
                },
            },
        )
    };
    vec![
        symbol(1, "a::one", 1, 10),
        symbol(2, "a::two", 1, 30),
        symbol(3, "b::three", 2, 10),
    ]
}

/// `SymbolId` -> raw `[u8; 8]` key used by the `SYMBOLS` table. Mirrors
/// `ariadne_storage`'s internal `encode_symbol_id`.
fn symbol_key(id: SymbolId) -> [u8; 8] {
    id.to_bytes()
}

/// Regenerates the committed `fixtures/schema-v2.redb`. Ignored so a normal
/// test run never rewrites the binary; invoke with `--ignored`.
#[test]
#[ignore = "regenerates fixtures/schema-v2.redb; run manually with --ignored"]
fn generate_v2_schema_fixture() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let scratch = tmp.path().join("scratch.redb");

    // Bootstrap a fresh database through the adapter so every table exists
    // with the expected definitions; drop the handle before mutating
    // directly.
    drop(RedbStorage::open(&scratch).expect("bootstrap scratch"));

    // Overwrite `SYMBOLS` with raw v2-encoded records + force the on-disk
    // schema version to 2. The `RedbStorage::open` above wrote the current
    // version (v3+) on bootstrap; the explicit downgrade represents a real
    // database that was last touched by a v2 binary.
    let db = Database::open(&scratch).expect("raw open");
    let txn = db.begin_write().expect("begin_write");
    {
        let mut meta = txn.open_table(META).expect("open meta");
        meta.insert("schema_version", &2u64).expect("downgrade");
        let mut symbols = txn.open_table(SYMBOLS).expect("open symbols");
        for (sid, v2) in known_symbols_v2() {
            let key = symbol_key(sid);
            let value = postcard::to_stdvec(&v2).expect("encode v2 record");
            symbols
                .insert(key.as_slice(), value.as_slice())
                .expect("insert v2");
        }
    }
    txn.commit().expect("commit");
    drop(db);

    let dest = fixture_v2_path();
    std::fs::create_dir_all(dest.parent().expect("fixtures parent")).expect("mkdir fixtures");
    std::fs::copy(&scratch, &dest).expect("write v2 fixture");
}

#[test]
fn v2_fixture_migrates_in_place_with_symbol_fields_preserved() {
    let fixture = fixture_v2_path();
    assert!(
        fixture.exists(),
        "missing {} — run `generate_v2_schema_fixture` with --ignored",
        fixture.display(),
    );

    let tmp = tempfile::tempdir().expect("tempdir");
    let work = tmp.path().join("index.redb");
    std::fs::copy(&fixture, &work).expect("copy v2 fixture");
    assert_eq!(
        on_disk_schema_version(&work),
        Some(2),
        "fixture must be a v2 database",
    );

    let storage = RedbStorage::open(&work).expect("v2 fixture must migrate, not error");
    let snap = storage.snapshot().expect("snapshot");

    for (_sid, v2) in known_symbols_v2() {
        let in_file = snap
            .symbols_in_file(v2.defining_file)
            .expect("symbols_in_file");
        let migrated = in_file
            .iter()
            .find(|r| r.canonical_name == v2.canonical_name)
            .unwrap_or_else(|| panic!("symbol {} missing after migration", v2.canonical_name));
        // First four v2 fields survive byte-identical (round-tripped).
        assert_eq!(migrated.canonical_name, v2.canonical_name);
        assert_eq!(migrated.kind, v2.kind);
        assert_eq!(migrated.defining_file, v2.defining_file);
        assert_eq!(migrated.defining_span, v2.defining_span);
        // New fields land at their defaults.
        assert_eq!(migrated.visibility, Visibility::Unknown);
        assert!(migrated.attributes.is_empty());
    }

    drop(storage);
    assert_eq!(
        on_disk_schema_version(&work),
        Some(3),
        "schema version advanced to v3 on disk",
    );
}
